//go:build !ignore_autogenerated

// Copyright 2024 Hedgehog
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	apimeta "go.githedgehog.com/fabric/api/meta"
	"go.githedgehog.com/fabricator/api/meta"
	"go.githedgehog.com/libmeta/pkg/alloy"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsStatus) DeepCopyInto(out *ComponentsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsStatus.
func (in *ComponentsStatus) DeepCopy() *ComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlConfig) DeepCopyInto(out *ControlConfig) {
	*out = *in
	if in.TLSSAN != nil {
		in, out := &in.TLSSAN, &out.TLSSAN
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DefaultUser.DeepCopyInto(&out.DefaultUser)
	if in.NTPServers != nil {
		in, out := &in.NTPServers, &out.NTPServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ControlObservability)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlConfig.
func (in *ControlConfig) DeepCopy() *ControlConfig {
	if in == nil {
		return nil
	}
	out := new(ControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlConfigRegistryUpstream) DeepCopyInto(out *ControlConfigRegistryUpstream) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlConfigRegistryUpstream.
func (in *ControlConfigRegistryUpstream) DeepCopy() *ControlConfigRegistryUpstream {
	if in == nil {
		return nil
	}
	out := new(ControlConfigRegistryUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNode) DeepCopyInto(out *ControlNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNode.
func (in *ControlNode) DeepCopy() *ControlNode {
	if in == nil {
		return nil
	}
	out := new(ControlNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeBootstrap) DeepCopyInto(out *ControlNodeBootstrap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeBootstrap.
func (in *ControlNodeBootstrap) DeepCopy() *ControlNodeBootstrap {
	if in == nil {
		return nil
	}
	out := new(ControlNodeBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeDummy) DeepCopyInto(out *ControlNodeDummy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeDummy.
func (in *ControlNodeDummy) DeepCopy() *ControlNodeDummy {
	if in == nil {
		return nil
	}
	out := new(ControlNodeDummy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeExternal) DeepCopyInto(out *ControlNodeExternal) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]meta.Addr, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeExternal.
func (in *ControlNodeExternal) DeepCopy() *ControlNodeExternal {
	if in == nil {
		return nil
	}
	out := new(ControlNodeExternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeList) DeepCopyInto(out *ControlNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeList.
func (in *ControlNodeList) DeepCopy() *ControlNodeList {
	if in == nil {
		return nil
	}
	out := new(ControlNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeManagement) DeepCopyInto(out *ControlNodeManagement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeManagement.
func (in *ControlNodeManagement) DeepCopy() *ControlNodeManagement {
	if in == nil {
		return nil
	}
	out := new(ControlNodeManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeSpec) DeepCopyInto(out *ControlNodeSpec) {
	*out = *in
	out.Bootstrap = in.Bootstrap
	out.Management = in.Management
	in.External.DeepCopyInto(&out.External)
	out.Dummy = in.Dummy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeSpec.
func (in *ControlNodeSpec) DeepCopy() *ControlNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ControlNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlNodeStatus) DeepCopyInto(out *ControlNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlNodeStatus.
func (in *ControlNodeStatus) DeepCopy() *ControlNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ControlNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlObservability) DeepCopyInto(out *ControlObservability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlObservability.
func (in *ControlObservability) DeepCopy() *ControlObservability {
	if in == nil {
		return nil
	}
	out := new(ControlObservability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlUser) DeepCopyInto(out *ControlUser) {
	*out = *in
	if in.AuthorizedKeys != nil {
		in, out := &in.AuthorizedKeys, &out.AuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlUser.
func (in *ControlUser) DeepCopy() *ControlUser {
	if in == nil {
		return nil
	}
	out := new(ControlUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabConfig) DeepCopyInto(out *FabConfig) {
	*out = *in
	in.Control.DeepCopyInto(&out.Control)
	in.Registry.DeepCopyInto(&out.Registry)
	in.Fabric.DeepCopyInto(&out.Fabric)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Observability.DeepCopyInto(&out.Observability)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabConfig.
func (in *FabConfig) DeepCopy() *FabConfig {
	if in == nil {
		return nil
	}
	out := new(FabConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabNode) DeepCopyInto(out *FabNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabNode.
func (in *FabNode) DeepCopy() *FabNode {
	if in == nil {
		return nil
	}
	out := new(FabNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabNodeList) DeepCopyInto(out *FabNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabNodeList.
func (in *FabNodeList) DeepCopy() *FabNodeList {
	if in == nil {
		return nil
	}
	out := new(FabNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabNodeSpec) DeepCopyInto(out *FabNodeSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]FabNodeRole, len(*in))
		copy(*out, *in)
	}
	out.Bootstrap = in.Bootstrap
	out.Management = in.Management
	out.Dummy = in.Dummy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabNodeSpec.
func (in *FabNodeSpec) DeepCopy() *FabNodeSpec {
	if in == nil {
		return nil
	}
	out := new(FabNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabNodeStatus) DeepCopyInto(out *FabNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabNodeStatus.
func (in *FabNodeStatus) DeepCopy() *FabNodeStatus {
	if in == nil {
		return nil
	}
	out := new(FabNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabOverrides) DeepCopyInto(out *FabOverrides) {
	*out = *in
	in.Versions.DeepCopyInto(&out.Versions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabOverrides.
func (in *FabOverrides) DeepCopy() *FabOverrides {
	if in == nil {
		return nil
	}
	out := new(FabOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricConfig) DeepCopyInto(out *FabricConfig) {
	*out = *in
	if in.VPCIRBVLANs != nil {
		in, out := &in.VPCIRBVLANs, &out.VPCIRBVLANs
		*out = make([]apimeta.VLANRange, len(*in))
		copy(*out, *in)
	}
	if in.VPCWorkaroundVLANs != nil {
		in, out := &in.VPCWorkaroundVLANs, &out.VPCWorkaroundVLANs
		*out = make([]apimeta.VLANRange, len(*in))
		copy(*out, *in)
	}
	if in.DefaultSwitchUsers != nil {
		in, out := &in.DefaultSwitchUsers, &out.DefaultSwitchUsers
		*out = make(map[string]SwitchUser, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.DefaultAlloyConfig.DeepCopyInto(&out.DefaultAlloyConfig)
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(apimeta.Observability)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricConfig.
func (in *FabricConfig) DeepCopy() *FabricConfig {
	if in == nil {
		return nil
	}
	out := new(FabricConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricVersions) DeepCopyInto(out *FabricVersions) {
	*out = *in
	if in.NOS != nil {
		in, out := &in.NOS, &out.NOS
		*out = make(map[apimeta.NOSType]meta.Version, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ONIE != nil {
		in, out := &in.ONIE, &out.ONIE
		*out = make(map[string]meta.Version, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricVersions.
func (in *FabricVersions) DeepCopy() *FabricVersions {
	if in == nil {
		return nil
	}
	out := new(FabricVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Fabricator) DeepCopyInto(out *Fabricator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fabricator.
func (in *Fabricator) DeepCopy() *Fabricator {
	if in == nil {
		return nil
	}
	out := new(Fabricator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Fabricator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricatorList) DeepCopyInto(out *FabricatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Fabricator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricatorList.
func (in *FabricatorList) DeepCopy() *FabricatorList {
	if in == nil {
		return nil
	}
	out := new(FabricatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricatorSpec) DeepCopyInto(out *FabricatorSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Overrides.DeepCopyInto(&out.Overrides)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricatorSpec.
func (in *FabricatorSpec) DeepCopy() *FabricatorSpec {
	if in == nil {
		return nil
	}
	out := new(FabricatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricatorStatus) DeepCopyInto(out *FabricatorStatus) {
	*out = *in
	in.Versions.DeepCopyInto(&out.Versions)
	in.LastAttemptTime.DeepCopyInto(&out.LastAttemptTime)
	in.LastAppliedTime.DeepCopyInto(&out.LastAppliedTime)
	in.LastStatusCheck.DeepCopyInto(&out.LastStatusCheck)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Components = in.Components
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricatorStatus.
func (in *FabricatorStatus) DeepCopy() *FabricatorStatus {
	if in == nil {
		return nil
	}
	out := new(FabricatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricatorVersions) DeepCopyInto(out *FabricatorVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricatorVersions.
func (in *FabricatorVersions) DeepCopy() *FabricatorVersions {
	if in == nil {
		return nil
	}
	out := new(FabricatorVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(GatewayObservability)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayObservability) DeepCopyInto(out *GatewayObservability) {
	*out = *in
	in.Dataplane.DeepCopyInto(&out.Dataplane)
	in.FRR.DeepCopyInto(&out.FRR)
	in.Unix.DeepCopyInto(&out.Unix)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayObservability.
func (in *GatewayObservability) DeepCopy() *GatewayObservability {
	if in == nil {
		return nil
	}
	out := new(GatewayObservability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayObservabilityDataplane) DeepCopyInto(out *GatewayObservabilityDataplane) {
	*out = *in
	if in.MetricsRelabel != nil {
		in, out := &in.MetricsRelabel, &out.MetricsRelabel
		*out = make([]alloy.ScrapeRelabelRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayObservabilityDataplane.
func (in *GatewayObservabilityDataplane) DeepCopy() *GatewayObservabilityDataplane {
	if in == nil {
		return nil
	}
	out := new(GatewayObservabilityDataplane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayObservabilityFRR) DeepCopyInto(out *GatewayObservabilityFRR) {
	*out = *in
	if in.MetricsRelabel != nil {
		in, out := &in.MetricsRelabel, &out.MetricsRelabel
		*out = make([]alloy.ScrapeRelabelRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayObservabilityFRR.
func (in *GatewayObservabilityFRR) DeepCopy() *GatewayObservabilityFRR {
	if in == nil {
		return nil
	}
	out := new(GatewayObservabilityFRR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayObservabilityUnix) DeepCopyInto(out *GatewayObservabilityUnix) {
	*out = *in
	if in.MetricsRelabel != nil {
		in, out := &in.MetricsRelabel, &out.MetricsRelabel
		*out = make([]alloy.ScrapeRelabelRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricsCollectors != nil {
		in, out := &in.MetricsCollectors, &out.MetricsCollectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayObservabilityUnix.
func (in *GatewayObservabilityUnix) DeepCopy() *GatewayObservabilityUnix {
	if in == nil {
		return nil
	}
	out := new(GatewayObservabilityUnix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayVersions) DeepCopyInto(out *GatewayVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayVersions.
func (in *GatewayVersions) DeepCopy() *GatewayVersions {
	if in == nil {
		return nil
	}
	out := new(GatewayVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityConfig) DeepCopyInto(out *ObservabilityConfig) {
	*out = *in
	in.Targets.DeepCopyInto(&out.Targets)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityConfig.
func (in *ObservabilityConfig) DeepCopy() *ObservabilityConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformVersions) DeepCopyInto(out *PlatformVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformVersions.
func (in *PlatformVersions) DeepCopy() *PlatformVersions {
	if in == nil {
		return nil
	}
	out := new(PlatformVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfig) DeepCopyInto(out *RegistryConfig) {
	*out = *in
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = new(ControlConfigRegistryUpstream)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfig.
func (in *RegistryConfig) DeepCopy() *RegistryConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchUser) DeepCopyInto(out *SwitchUser) {
	*out = *in
	if in.AuthorizedKeys != nil {
		in, out := &in.AuthorizedKeys, &out.AuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchUser.
func (in *SwitchUser) DeepCopy() *SwitchUser {
	if in == nil {
		return nil
	}
	out := new(SwitchUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLABVersions) DeepCopyInto(out *VLABVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLABVersions.
func (in *VLABVersions) DeepCopy() *VLABVersions {
	if in == nil {
		return nil
	}
	out := new(VLABVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Versions) DeepCopyInto(out *Versions) {
	*out = *in
	out.Platform = in.Platform
	out.Fabricator = in.Fabricator
	in.Fabric.DeepCopyInto(&out.Fabric)
	out.Gateway = in.Gateway
	out.VLAB = in.VLAB
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Versions.
func (in *Versions) DeepCopy() *Versions {
	if in == nil {
		return nil
	}
	out := new(Versions)
	in.DeepCopyInto(out)
	return out
}
