{
 "title": "Interfaces",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   {
    "name": "node",
    "label": "Switch",
    "query": {
     "query": "label_values(fabric_agent_agent_version,hostname)"
    }
   },
   { "name": "interface", "label": "Interface", "query": { "query": "label_values(interface)" } }
  ]
 },
 "panels": [
  {
   "title": "Interface status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Admin Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_admin_status{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"} > bool 0",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Operational status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_oper_status{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"} > bool 0",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "Interface stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pkts in/out total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "PPS rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_pkts_per_second{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_pkts_per_second{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "Interface Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_utilization{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_utilization{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "Bits per second rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_bits_per_second{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_bits_per_second{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "Unicast pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_unicast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_unicast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "Errors and discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_discards{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input discards"
    },
    {
     "expr": "fabric_agent_interface_in_errors{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input errors"
    },
    {
     "expr": "fabric_agent_interface_out_errors{hostname=\"$node\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} output errors"
    },
    {
     "expr": "fabric_agent_interface_out_discards{hostname=\"$node\", interface=\"$interface\"}",
     "legendFormat": "{{interface}} output discards"
    }
   ]
  },
  {
   "title": "Multicast pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_multicast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_multicast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  },
  {
   "title": "Broadcast pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fabric_agent_interface_in_broadcast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} input"
    },
    {
     "expr": "fabric_agent_interface_out_broadcast_pkts{hostname=\"$node\", interface=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{interface}} output"
    }
   ]
  }
 ]
}