{
 "title": "Platform",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   {
    "name": "node",
    "label": "Switch",
    "query": {
     "query": "label_values(fabric_agent_agent_version,hostname)"
    }
   },
   { "name": "interface", "label": "Interface", "query": { "query": "label_values(interface)" } }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "description": "Temperature that picked by sensors from different parts of the switch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fabric_agent_platform_sensor_temperature{hostname=\"$node\", env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FAN Speed",
   "type": "timeseries",
   "description": "Fan speed located on PSU and trays.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "fabric_agent_platform_fan_speed{hostname=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PSU input/output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "fabric_agent_platform_psu_output_power{hostname=\"$node\", env=\"$env\"}",
     "legendFormat": "PSU Voltage Output"
    },
    {
     "expr": "fabric_agent_platform_psu_input_power{hostname=\"$node\"}",
     "legendFormat": "PSU Voltage Input"
    }
   ]
  },
  {
   "title": "Optic Transceiver Temperature",
   "type": "timeseries",
   "description": "Temperature of transceiver with DOM support",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fabric_agent_transceiver_temperature{hostname=\"$node\", transceiver=~\"$interface\", env=\"$env\"}",
     "legendFormat": "{{transceiver}}"
    }
   ]
  }
 ]
}