{
 "title": "Logs",
 "description": "Critical Fabric Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {}
   },
   {
    "name": "node",
    "label": "Switch",
    "query": {}
   },
   {
    "name": "file",
    "label": "File",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Syslog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/syslog\", env=\"$env\", hostname=\"$node\"} |~ `(?i)ERROR`"
      }
     ]
    },
    {
     "title": "Kernel",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/syslog\", env=\"$env\", hostname=\"$node\"} |~ `kernel:`"
      }
     ]
    },
    {
     "title": "BGP Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/syslog\", env=\"$env\", hostname=\"$node\"} |~ `(?i)bgp`"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/agent.log\", hostname=\"$node\", env=\"$env\"} |= `ERROR`"
      }
     ]
    }
   ]
  },
  {
   "title": "Full log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log for given File",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{env=\"$env\", filename=\"$file\", hostname=\"$node\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}