{
 "title": "Fabric",
 "description": "Fabric underlay connection monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   {
    "name": "node",
    "label": "Switch",
    "query": {
     "query": "label_values(fabric_agent_agent_version,hostname)"
    }
   },
   { "name": "vrf", "label": "VRF", "query": { "query": "label_values(vrf)" } },
   { "name": "neighbor", "label": "Neighbor", "query": { "query": "label_values(neighbor)" } }
  ]
 },
 "panels": [
  { "title": "BGP Neighbor State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BGP Neighbor",
   "type": "timeseries",
   "description": "BGP Neighbor configuration status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_enabled{hostname=\"$node\", vrf=~\"$vrf\", neighbor=~\"$neighbor\", env=\"$env\"} == 1",
     "legendFormat": "{{neighbor}}"
    }
   ]
  },
  {
   "title": "BGP Established",
   "type": "timeseries",
   "description": "Session State between given node and BGP Neighbor. True if state is Established.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_session_state{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"} == bool 6",
     "legendFormat": "{{neighbor}}"
    }
   ]
  },
  { "title": "BGP Neighbors Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BGP Dropped connections",
   "type": "timeseries",
   "description": "Number of BGP Dropped connections for each neighbor.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_connections_dropped{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "{{neighbor}}"
    }
   ]
  },
  {
   "title": "BGP Prefixes",
   "type": "timeseries",
   "description": "Number of route prefixes exported or received from each BGP Neighbor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_prefixes_received{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "Received from {{neighbor}} {{afisafi}}"
    },
    {
     "expr": "fabric_agent_bgp_neighbor_prefixes_sent{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=\"$vrf\", env=\"$env\"}",
     "legendFormat": "Sent to {{neighbor}} {{afisafi}}"
    }
   ]
  },
  {
   "title": "BGP Updates",
   "type": "timeseries",
   "description": "Number of BGP Route Update messages sent and received from each BPG Neighbor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_messages_received_update{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "Received from {{neighbor}}"
    },
    {
     "expr": "fabric_agent_bgp_neighbor_messages_sent_update{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "Sent to {{neighbor}}"
    }
   ]
  },
  {
   "title": "Keepalives",
   "type": "timeseries",
   "description": "Counter of Keepalive messages between each BG neighbor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fabric_agent_bgp_neighbor_messages_received_keepalive{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "Received from {{neighbor}}"
    },
    {
     "expr": "fabric_agent_bgp_neighbor_messages_sent_keepalive{hostname=\"$node\", neighbor=~\"$neighbor\", vrf=~\"$vrf\", env=\"$env\"}",
     "legendFormat": "Sent to {{neighbor}}"
    }
   ]
  }
 ]
}