{
 "title": "Switch Critical Resources",
 "description": "Switch ASIC Critical Programmable Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Env", "query": { "query": "label_values(env)" } },
   {
    "name": "node",
    "label": "Switch",
    "query": {
     "query": "label_values(fabric_agent_agent_version,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ACL Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available ACL Groups",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_acl_groups_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "{{direction}} {{type}}"
      }
     ]
    },
    {
     "title": "Used ACL Groups",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_acl_groups_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "{{direction}} {{type}}"
      }
     ]
    },
    {
     "title": "Used ACL Tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_acl_tables_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "{{direction}} {{type}}"
      }
     ]
    },
    {
     "title": "Available ACL Tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_acl_tables_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "{{direction}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 Neighbors usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_ipv4_neighbors_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_ipv4_neighbors_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    },
    {
     "title": "IPv4 Nexthops usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_ipv4_nexthops_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_ipv4_nexthops_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    },
    {
     "title": "IPv4 Routes usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_ipv4_routes_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_ipv4_routes_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nexthop Groups usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_nexthop_groups_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_nexthop_groups_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    },
    {
     "title": "Nexthop Group Members usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_nexthop_group_members_available{env=\"env-1\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_nexthop_group_members_used{env=\"env-1\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    },
    {
     "title": "Forwarding DB entries usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_fdb_entries_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_fdb_entries_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    },
    {
     "title": "IP Multicast Table usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fabric_agent_critical_resource_ipmc_entries_available{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Available {{hostname}}"
      },
      {
       "expr": "fabric_agent_critical_resource_ipmc_entries_used{env=\"$env\", hostname=\"$node\"}",
       "legendFormat": "Used {{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}