# Minimal Prometheus Helm values for test/demo

alertmanager:
  enabled: false
pushgateway:
  enabled: true
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false

configmapReload:
  prometheus:
    enabled: false

server:
  image:
    repository: prom/prometheus
    tag: v3.7.0

  persistentVolume:
    enabled: false  # no PVC for demo use

  service:
    type: NodePort
    nodePort: 30900

  nodeSelector:
{{ .NodeSelectorBlock }}
  tolerations:
{{ .TolerationsBlock }}

  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  # Enable remote write receiver for Alloy agents to push metrics
  extraFlags:
    - web.enable-remote-write-receiver

  # Basic scraping config for Prometheus itself and annotated pods
  extraScrapeConfigs: |
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

