run:
  timeout: 10m
  allow-parallel-runners: true
  build-tags:
    - containers_image_openpgp
    - containers_image_storage_stub

linters:
  disable-all: true
  # Look at this for details: https://golangci-lint.run/usage/linters/
  enable:
    # enabled by default
    - typecheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # disabled by default
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - depguard
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - err113
    - gofmt
    - goimports
    - gosec
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck

linters-settings:
  exhaustive:
    check:
      - switch
      - map
  reassign:
    patterns:
      - ".*"
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors$"
            desc: use stdlib errors package

# TODO remove after controller is used
issues:
  exclude-files:
    - test
    - internal
