replicaCount: 1
image:
  repository: {{ .Repo }}
  pullPolicy: IfNotPresent
  tag: {{ .Tag }}

service:
  type: NodePort
  port: 5000
  nodePort: {{ .Port }}

httpGet:
  scheme: HTTPS

persistence: true
pvc:
  create: true
  storage: 30Gi

mountSecret: false

externalSecrets:
  - secretName: {{ .TLSSecret }}
    mountPath: /tls
  - secretName: {{ .HtpasswdSecret }}
    mountPath: /htpasswd
  - secretName: {{ .UpstreamSecret }}
    mountPath: /upstream

mountConfig: true

configFiles:
  config.json: |-
{{ .Config | indent 4 }}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: "30s"
    path: "/metrics"

resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 100m
