apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control-proxy.fullname" . }}-config
  labels:
    {{- include "control-proxy.labels" . | nindent 4 }}
data:
  tinyproxy.conf: |-
{{.Values.config | indent 4 }}
  filters.conf: |-
{{- range .Values.urls }}
{{ . | indent 4 }}
{{- end }}
