apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyproxy-config
data:
  tinyproxy.conf: |-
{{- range .Values.TinyproxyConfig }}
{{ . | indent 4 }}
{{- end }}
  filters.conf: |-
{{- range .Values.tinyproxyURLs }}
{{ . | indent 4 }}
{{- end }}
