apiVersion: v1
kind: Service
metadata:
  name: {{ template "chrony.fullname" . }}-udp
  labels:
    app: {{ template "chrony.name" . }}
    chart: {{ template "chrony.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceUDP.annotations }}
  annotations:
{{ toYaml .Values.serviceUDP.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceUDP.type }}
  {{- if .Values.serviceUDP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceUDP.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceUDP.type "NodePort") (eq .Values.serviceUDP.type "LoadBalancer") }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
  - port: 123
    {{- if gt (int .Values.serviceUDP.nodePort) 0 }}
    nodePort: {{ .Values.serviceUDP.nodePort }}
    {{- end }}
    targetPort: ntp
    protocol: UDP
    name: ntp
  selector:
    app: {{ template "chrony.name" . }}
    release: {{ .Release.Name }}
