# This rule is not used by the project fabricator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over fabricator.githedgehog.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fabricator
    app.kubernetes.io/managed-by: kustomize
  name: fabricator-node-admin-role
rules:
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - nodes/status
  verbs:
  - get
