# permissions for end users to view controlnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fabricator
    app.kubernetes.io/managed-by: kustomize
  name: fabricator-controlnode-viewer-role
rules:
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - controlnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - controlnodes/status
  verbs:
  - get
