# permissions for end users to edit controlnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fabricator
    app.kubernetes.io/managed-by: kustomize
  name: fabricator-controlnode-editor-role
rules:
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - controlnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - controlnodes/status
  verbs:
  - get
