replicaCount: 1

image:
  repository: "cturra/ntp"
  tag: latest
  pullPolicy: IfNotPresent

hostNetwork: false

serviceUDP:
  type: NodePort
  nodePort: 0
  externalTrafficPolicy: Local
  loadBalancerIP: "" # a fixed LoadBalancer IP
  annotations:
    {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: chrony

# Probes configuration
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5

# Do note, to configure more than one server, you must use a comma delimited list WITHOUT spaces.
ntpServers: "time.cloudflare.com,time1.google.com,time2.google.com,time3.google.com,time4.google.com"

# extraEnvironmentVars is a list of extra enviroment variables to set for chrony to use
extraEnvVars: {}

# extraEnvVarsSecret is a list of secrets to load in as environment variables.
extraEnvVarsSecret:
  {}
  # env_var:
  #   name: secret-name
  #   key: secret-key

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
