apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyproxy-config
data:
  tinyproxy.conf: |
{{ $.Files.Get "configmap/tinyproxy.conf" | indent 4 }}
  filters.conf: |
{{ $.Files.Get "configmap/filters.conf" | indent 4 }}
