name: CI-HW

concurrency:
  group: ci-hw-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  vlab:
    runs-on: hlab
    timeout-minutes: 600

    strategy:
      fail-fast: false
      matrix:
        include:
          - fabricmode: spine-leaf
            includeonie: true
            buildmode: iso

    steps:
      - name: Runner host
        run: |
          echo "$KUBE_NODE"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Setup local registry
        run: |
          just --timestamp _localreg &

      - name: Build hhfab
        run: |
          just --timestamp oci_repo=127.0.0.1:30000 oci=http push

      - name: hhfab init and vlab up
        env:
          HHFAB_REG_REPO: 127.0.0.1:30000
          HHFAB_CONTROL_NODE_MGMT_LINK: pci@0000:01:00.3
        run: |
          export PATH=$PATH:$(pwd)/bin
          wget -O wiring.yaml https://gist.githubusercontent.com/Frostman/993c0bb21b5547a08a459f51d1ef65b7/raw/b07f95abd328ede74e832134a17bd4972c0b11ac/env-ci-1.wiring.yaml
          bin/hhfab init -v --dev -m ${{ matrix.fabricmode }} --include-onie=${{ matrix.includeonie }} -w wiring.yaml
          bin/hhfab vlab up -v --ready switch-reinstall --ready setup-vpcs --ready test-connectivity --ready exit --mode=${{ matrix.buildmode }}

      - name: Dump local registry logs
        if: ${{ always() }}
        run: |
          cat .zot/log

      - name: Setup tmate session for debug
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
        with:
          limit-access-to-actor: true
